[package]
name = "remote-obj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["remote-obj-derive"]

[dependencies]
remote-obj-derive = { path = "remote-obj-derive" }
